Add configuration to specifiy abolute path to d2 executable
terrastruct/d2-vscode pull request #37
Opened 2023-01-25 19:59 UTC by samsonasu

I couldn't figure out how to get VSCode to get `d2` on my path on linux (arch btw) so I added a configuration to override with the absolute path.  It defaults to looking on the path. 

Also made some minor updates to the README.  

May help folks experiencing https://github.com/terrastruct/d2-vscode/issues/33 as well.

2023-01-25 20:04 UTC, BarryNolte requested changes
The new path setting needs to be used in documentFormatter.ts too.  Otherwise, looks good.

2023-01-25 20:06 UTC, BarryNolte commented on src/docToPreviewGenerator.ts
> -      const proc = spawnSync("d2", [
This needs to be done in documentFormatter.ts too.

2023-01-25 20:08 UTC, BarryNolte requested changes
Other than the small change I requested, looks good.

2023-01-25 20:08 UTC, BarryNolte commented on src/docToPreviewGenerator.ts
> +      const d2Path: string = ws.get("execPath", "d2");
This needs to be done in documentFormatter.ts too.

2023-01-25 21:07 UTC, samsonasu commented
Good catch.  I updated the logic in the formatter as well.  Thanks for the quick review!

2023-01-25 21:12 UTC, gavin-ts approved these changes

2023-01-25 21:17 UTC, gavin-ts commented
> could you set up commit signing please? [#557 (comment)](https://github.com/terrastruct/d2/pull/557#issuecomment-1367468730)

https://github.com/terrastruct/d2/pull/690#issuecomment-1397746636

2023-01-26 00:21 UTC, samsonasu commented
GPG signing set up and verified!

2023-01-26 00:30 UTC, merged